name: Build and Push to Docker Hub

on:
  push:
    paths:
      - "punto_3/index.html"  # Dispara el workflow cuando se modifica index.html
    branches:
      - main  # Cambiar en caso de usar otra rama

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Iniciar sesión en Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Construir la imagen de Docker
        run: |
          docker build -t gbzz24/assessment3:latest ./punto_3

      - name: Publicar la imagen en Docker Hub
        run: |
          docker push gbzz24/assessment3:latest
